# Generated by Django 4.1.2 on 2022-10-06 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название компании')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН организации')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП организации')),
                ('token_key', models.CharField(max_length=100, unique=True, verbose_name='Токен ОФД')),
            ],
            options={
                'verbose_name': 'Огранизация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название магазина')),
                ('branch_id', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='ID в системе ОФД')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ofdload.company')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Kkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование ККТ в ОФД')),
                ('model', models.CharField(max_length=100, verbose_name='Модель ККТ')),
                ('status', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Статус кассы')),
                ('reg_number', models.CharField(max_length=20, verbose_name='Рег.номер')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес регистрации')),
                ('date_fn', models.CharField(max_length=30, verbose_name='Дата окончания ФН')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ofdload.shop')),
            ],
            options={
                'verbose_name': 'ККТ',
                'verbose_name_plural': 'ККТ',
                'ordering': ['name'],
            },
        ),
    ]
