# Generated by Django 4.1.2 on 2022-10-14 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ofdload', '0002_remove_kkt_shop_id_kkt_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='renew',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kkt',
            name='renew',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kkt',
            name='status',
            field=models.CharField(max_length=100, verbose_name='Статус кассы'),
        ),
    ]
