# Generated by Django 4.1.2 on 2022-10-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofdload', '0004_receipts'),
    ]

    operations = [
        migrations.CreateModel(
            name='receipts_office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscalSign', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Фискальный признак документа')),
                ('receiptDate', models.DateTimeField(verbose_name='Дата/время чека по ККТ')),
                ('receiptCode', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Код формы ФД')),
                ('totalSum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма чека')),
            ],
            options={
                'verbose_name': 'Чек офиса',
                'verbose_name_plural': 'Чеки офиса',
                'ordering': ['fiscalSign'],
            },
        ),
    ]
